lzc-sdk-version: "0.1"
name: IPTV检查器
package: cloud.lazycat.app.iptv-checker
version: 4.1.4
description: IPTV检查工具，请检查您的播放列表是否可用
homepage: https://github.com/zhimin-dev/iptv-checker
author: zhimin-dev
application:
  subdomain: iptv-checker
  background_task: true
  multi_instance: false
  gpu_accel: false
  kvm_accel: false
  usb_accel: false
  routes:
    - /=http://iptv-checker.cloud.lazycat.app.iptv-checker.lzcapp:8089/
services:
  iptv-checker:
    image: registry.lazycat.cloud/czyt/zmisgod/iptvchecker:60598750262c8c6e
    binds:
      - /lzcapp/var/output:/app/static/output
      - /lzcapp/var/input:/app/static/input
