package: cloud.lazycat.app.iptv-checker
version: 5.0.2
name: IPTV检查器
description: "IPTV检查工具，请检查您的播放列表是否可用"
min_os_version: "1.5.0"
homepage: https://github.com/zhimin-dev/iptv-checker
author: zhimin-dev
locales:
  zh:
    description: "IPTV检查工具，请检查您的播放列表是否可用"
    name: IPTV检查器
  en:
    description: "IPTV checker - verify whether your playlist is playable"
    name: IPTV Checker
